### ISSUE TITLE
Cannot enable vuecket, no artifacts in central

### ISSUE THREAD

**Issue by MiMo42** [OrienteerBAP/vuecket#8]
Trying to enable vuecket gives me:
```
Could not find org.orienteer.vuecket:vuecket:1.0-SNAPSHOT.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/org/orienteer/vuecket/vuecket/1.0-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/org/orienteer/vuecket/vuecket/1.0-SNAPSHOT/vuecket-1.0-SNAPSHOT.pom
Required by:
    project :
```
Looks like there is no artifact in central:
https://repo.maven.apache.org/maven2/org/orienteer/

**Comment by PhantomYdn** [comment]
@MiMo42 , Vuecket is in active development and we are just about to issue official version 1.0.
But you can already use it with version `1.0-SNAPSHOT`. To be able to use SNAPSHOT version - please make sure that you have corresponding repository configured in your pom. It should be:

```xml
<repository>
	<id>Sonatype Nexus</id>
	<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
	<releases>
		<enabled>false</enabled>
	</releases>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```
Here is direct link to make sure that `1.0-SNAPSHOT` is here: https://oss.sonatype.org/content/repositories/snapshots/org/orienteer/vuecket/vuecket/

**Comment by PhantomYdn** [comment]
@MiMo42, I updated readme about this under commit 00631133e68caa0411c8ed5aed2720af70561e1d. Please let me know if you have any issues with Vuecket! We internally see power of Vuecket: no REST needed, data is flowing between serverside and clientside very easily. It's pleasure to code on Wicket + Vue (Vuecket), but we are not sure that learning curve is not high to get there...
