### ISSUE TITLE
Custom VueDescriptors ignored

### ISSUE THREAD

**Issue by MiMo42** [OrienteerBAP/vuecket#9]
I need to use Vue components from a private WebJar and tried to use a custom VueWebJarDescriptor for that.

```
VueWebJarDescriptor descriptor = new VueWebJarDescriptor("vue-components/current/WeekChart/WeekChart.umd.min.js", "Vue.use(WeekChart)");
add(new VueComponent<String>("app")
        .add(new Chart("chart")
                .setVueDescriptor(descriptor)
        ));
```
VuecketInitializer's init ignores the existing custom VueDescriptor on the component.                
Instead, Vuecket calls IVueDescriptor's lookupDescriptor method, which cannot match.

I think, Vuecket should use component's custom VueDescriptor if available.

I'd also like Vuecket's lookup to be able to add custom descriptors by some kind of registration. 

My custom descriptor utilizes Wicket's WebjarsJavaScriptResourceReference to get the resource located in a WebJar.

**Comment by PhantomYdn** [comment]
@MiMo42, could you please share code of your `VueWebJarDescriptor`?

I have just a slightly different proposal - your feedback is interesting:
1) Instead of custom descriptor: use @VueNpm annotation on class `Chart`
2) Specify proper `INPMPackageProvider` on `VueSettings`. By default it uses CDN, but can be retargeted to something local and etc.
3) If there is no local CDN with private package: you can start using https://github.com/OrienteerBAP/JNPM - which can be configured to local NPM repository (and it will work as local NPM proxy)

If you are already packing Vue components inside your War (btw, you can use JNPM for that as well: it much more easier in comparison with WebJars): using INPMPackageProvider will be the best choice. Problems here might be if different packages should be loaded from different places: for example - your private NPM package from your repository, but everything else from public one.

**Comment by PhantomYdn** [comment]
Created ticket #10 to create INPMPackageProvider for embedded WebJars. In this case it will be much more easier for you. Will push it soon.

**Comment by MiMo42** [comment]
My VueWebWarDescriptor:

```
public class VueWebJarDescriptor implements IVueDescriptor  {
    private String packageName;
    private String enablementScript;
    private ResourceReference reference;

    public VueWebJarDescriptor(String packageName, String enablementScript) {
        JavaScriptResourceReference ref = new WebjarsJavaScriptResourceReference(packageName);
        this.packageName = packageName;
        this.reference = ref;
        this.enablementScript = enablementScript;
    }

    @Override
    public String getName() { return this.packageName; }

    public String getPackageName() {
        return packageName;
    }
    public String getEnablementScript() {
        return enablementScript;
    }
    public ResourceReference getReference() {
        return this.reference;
    }

    public static VueWebJarDescriptor create(Class<?> clazz) {
        return null; // unfortunately, no annotation yet
    }

    @Override
    public VueComponentHeaderItem rootHeaderItem(String elementId) {
        throw new WicketRuntimeException("WebJar based vue descriptor is not supported for root Vue elements");
    }

    @Override
    public VueComponentHeaderItem componentHeaderItem() {
        return new VueComponentHeaderItem(getPackageName(),
                JavaScriptHeaderItem.forReference(
                        getReference()),
                OnDomReadyHeaderItem.forScript(getEnablementScript()));
    }
}

```

**Comment by PhantomYdn** [comment]
@MiMo42 , just pushed changes for #10. To use packed libraries by WebJars: please use new `org.orienteer.vuecket.npmprovider.WebJarsNPMPackageProvider.WEBJARS_PROVIDER`. You can setup it by calling `VueSettings.get().setNpmPackageProvider(WebJarsNPMPackageProvider.WEBJARS_PROVIDER);` or alternatively you can specify NPM Package Provider per component. To set it you can use something like this: `org.orienteer.vuecket.npmprovider.WebJarsNPMPackageProvider.WEBJARS_PROVIDER.setAsCustomNPMPackageProviderFor(component)`

**Comment by MiMo42** [comment]
Looks interesting!
The 1.0-Snapshot does not reflect the commits related to #10.
Can you publish a new version to https://oss.sonatype.org/content/repositories/snapshots/, please ?

To set a package provider by component results in additional boilerplate code.
That's why I'd like to see a package provider option in annotation.

**Comment by PhantomYdn** [comment]
Strange... Pushed again. Please check.

**Comment by PhantomYdn** [comment]
@MiMo42 , any luck? Can this ticket be closed?

**Comment by MiMo42** [comment]
Yes, thank you!
